#!/bin/sh
yay --removemake --nocleanmenu --nodiffmenu --noeditmenu --noupgrademenu -Sy \
    acpi                            \
    alacritty                       \
    arc-gtk-theme                   \
    arc-icon-theme                  \
    autojump                        \
    autorandr                       \
    brillo                          \
    bluez                           \
    bluez-utils                     \
    capitaine-cursors               \
    cifs-utils                      \
    code                            \
    dust                            \
    firefox	                        \
    fish                            \
    fwupd                           \
    gimp                            \
    git-credential-gopass           \
    gnupg                           \
    gopass                          \
    gopass-jsonapi                  \
    grim                            \
    grimshot                        \
    htop                            \
    jq                              \
    lf                              \
    librewolf-bin                   \
    lutris                          \
    lxappearance                    \
    make                            \
    man-db                          \
    man-pages                       \
    mpv                             \
    most                            \
    neofetch                        \
    neovim                          \
    neovim-drop-in                  \
    nfs-utils                       \
    noto-fonts                      \
    ntfs-3g                         \
    openssh                         \
    otf-font-awesome                \
    p7zip                           \
    pacman-contrib                  \
    pacman-mirrorlist               \
    pamixer                         \
    proton-ge-custom-bin            \
    polkit                          \
    powertop                        \
    rsync                           \
    rust                            \
    scrot                           \
    slock                           \
    steam                           \
    sway                            \
    swaybg                          \
    swayidle                        \
    swaylock                        \
    sxiv                            \
    ttf-fira-code                   \
    ttf-fira-mono                   \
    ttf-fira-sans                   \
    ttf-liberation                  \
    udisks2                         \
    upower                          \
    wine                            \
    wl-clipboard                    \
    x11-ssh-askpass                 \
    xclip                           \
    xdg-desktop-portal-wlr          \
    xorg-server                     \
    xorg-apps                       \
    xorg-xinit                      \
    xorg-xsetroot                   \
    xorg-xwayland                   \
    zsh

